### ISSUE TITLE
status and license?

### ISSUE THREAD

**Issue by cep21** [rockyhmchen/terraform-provider-sealedsecrets#1]
Hi,

I'm looking exactly for a sealed secrets provider!  Do you still use this module?  What's the LICENSE of this code?

**Comment by rockyhmchen** [comment]
Hi @cep21,
Yes, I do. My current company is using it as I created for our current project.  However, I have made short work of it. As you can see that there is no test, README and LICENSE. I have planed to add README later and will probably choose MIT as the license.

**Comment by rockyhmchen** [comment]
I have added README and LICENSE.
